trigger:
  branches: { include: ["*"] }
  tags: { include: [v*] }

pr:
  branches: { include: [main] }

resources:
  repositories:
    - repository: ci
      type: git
      name: VPOS/vpos-mono-package-mgr
      ref: refs/heads/main

extends:
  template: azure/templates/node-lib.yml@ci
  parameters:
    consumerPath: "vpos-dashboard"
    nodeVersion: "18.x"
    mainBranch: "refs/heads/main"
    runChangelogSync: true
